# Generated by Django 4.1.2 on 2025-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("structure_file", models.FileField(upload_to="structures/")),
                ("features_file", models.FileField(upload_to="features/")),
                ("performance_k", models.CharField(max_length=255)),
                ("performance_tan_omega", models.CharField(max_length=255)),
                ("performance_tck", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("reference", models.CharField(max_length=255)),
                ("uploader", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
