# Generated by Django 4.1.2 on 2025-01-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cifapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="original_features_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="original_structure_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="record",
            name="structure_file",
            field=models.FileField(upload_to="sturestrus/"),
        ),
    ]
